### ISSUE TITLE
where is the resnet50-19c8e357.pth

### ISSUE THREAD

**Issue by FJP123** [daodaofr/hypergraph_reid#5]
when I want to train the model ,terminal shows that pretrained model resnet50-19c8e357.pth is no such file.
hope to get reply.
thanks!

**Comment by daodaofr** [comment]
hi, you can download the resnet50 model from "https://download.pytorch.org/models/resnet50-19c8e357.pth", and replace the line with your path:
https://github.com/daodaofr/hypergraph_reid/blob/40fa99006db21d4765f5f9ab99fa586c3ec04a36/models/ResNet_hypergraphsage_part.py#L543

**Comment by FJP123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "daodaofr/hypergraph_reid"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 晚上11:22
收件人:&nbsp;"daodaofr/hypergraph_reid"<hypergraph_reid@noreply.github.com&gt;;
抄送:&nbsp;"北京交通大学 傅京鹏"<1197658496@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [daodaofr/hypergraph_reid] where is the resnet50-19c8e357.pth (#5)

您好 
 
我叫傅京鹏，北京交通大学的研一学生，最近在看您的这篇超图reid论文和代码，但是代码几乎没有注释，困难重重，是否可以解释下build_adj_full_d（）的作用和函数的几个参数意思，另外还有返回的adj代表的什么。

这将对我的学习有很大帮助，真诚的希望得到您的回复。

**Comment by daodaofr** [comment]
Hi @FJP123 

build_adj_full_d() is designed to return the adjacency matrix for the hypergraph. The input arguments are the temporal range, the number of part partitions. You can ignore d because we don't use it here.

Building the adjacency matrix is a basic step in GCN, please refer to https://github.com/Diego999/pyGAT/blob/b7b68866739fb5ae6b51ddb041e16f8cef07ba87/utils.py#L28
